### PR TITLE
Add support for Windows

### PR DESCRIPTION
**Pull request by dafyddj**
This addition installs a code-signing certificate for OpenVPN so that the TAP driver can be installed without user intervention. This depends on using salt-winrepo(-ng).

### CODE REVIEW

**Comment by dafyddj** [comment]
This works in a basic sense, but config.sls needs further work in terms of file permissions and ownership.

**Comment by alxwr** [comment]
> This depends on using salt-winrepo(-ng).

```sls
{% if salt['grains.get']('os_family') == 'Windows' %}
include:
  - salt-winrepo-ng
{% endif%}
```

Is there a reason you did not put this at the top of `init.sls`?

**Comment by alxwr** [comment]
Tested it on FreeBSD, Debian and Ubuntu. LGTM. Any windows user here who can test this also?

**Comment by dafyddj** [comment]
Sorry, maybe I was unclear. There is no package salt-winrepo/ng, it's just that this is pretty useless if somebody doesn't have use winrepo in their saltstack setup.

**Comment by alxwr** [comment]
Ok, I thought you were talking about a hard dependency. :-)

> `config.sls` needs further work in terms of file permissions and ownership.
I'm interested: to solve which problem?

**Comment by dafyddj** [comment]
Salt complains that file permissions/ownership are not supported on Windows, and some file.managed states fail, but I have been looking at it.

**Comment by alxwr** [comment]
Tested on Ubuntu 14.04, Debian 8.6 and FreeBSD 10.3. (Unfortunately I've got no Windows setup to test.)

Thanks!

**Pull request merged**
