### PR TITLE
Feature/more options

### PR DESCRIPTION
**Pull request by alexhayes**
This PR adds the following options;

- `auth_user_pass`
- `auth_user_pass_content`
- `fast_io`
- `fragment`
- `key-direction`
- `keysize`
- `mssfix`
- `pull`
- `rcvbuf`
- `route-delay`
- `route-method`
- `route-pull`
- `tls-client`
- `sndbuf`

It also moves the `route` option from the `server.jinja` into the `common_opts.jinja` as this is a valid option in OpenVPN for both server and client.

### CODE REVIEW

**Comment by alxwr** [comment]
Thank you!
I'll test it against Debian Jessie, Ubuntu 14.04, 16.04 and FreeBSD 10.03.

Can anyone test this on CentOS (or others)?

**Comment by alexhayes** [comment]
@alxwr I don't have any CentOS machines running salt but I could potentially run up a VM. FYI I have tested a OpenVPN client on Ubuntu 16.04.

**Comment by javierbertoli** [comment]
I can try it on a couple of CentOS over the weekend if that's OK with you

**Comment by alxwr** [comment]
@javierbertoli sounds great! Thanks!

**Comment by javierbertoli** [comment]
Tested these changes on a Debian, Centos 6 and Centos 7 and they all worked OK. If you agree, I'll merge tomorrow morning.

**Comment by alxwr** [comment]
@javierbertoli Please do so! Thank you for testing!

**Pull request merged**
