### PR TITLE
Ipv6 support

### PR DESCRIPTION
**Pull request by t0fik**
Added IPv6 support to formula

### CODE REVIEW

**Comment by mthibaut** [comment]
Ah darn, I didn't see you had contributed the same thing. I'll remove my IPv6 pull request and check out yours. Many eyes and so on.

**Comment by t0fik** [comment]
Ok, great :)

**Comment by mthibaut** [comment]
I can't edit your PR, so I created PR https://github.com/saltstack-formulas/openvpn-formula/pull/81 instead.

**Comment by t0fik** [comment]
Closed due to combined #78 and #80 PRs in #81

**Pull request closed without merging**
