### PR TITLE
Fix #71

### LINKED ISSUE #71: config.auth_user_pass: no split needed
https://github.com/saltstack-formulas/openvpn-formula/pull/69#issuecomment-323763459

### PR DESCRIPTION
**Pull request by alxwr**
@dafyddj please have a look at this PR. It's my attempt to fix #71. Does it fit your needs?

### CODE REVIEW

**Comment by dafyddj** [comment]
Hi @alxwr, if I'm not mistaken, doesn't this require a similar change in ```openvpn\files\common_opts.jinja```?

**Comment by alxwr** [comment]
@dafyddj you're right! Thanks! I'll add that.

**Comment by alxwr** [comment]
Fix tested on FreeBSD 10.3, Ubuntu 14.04 and Debian 8.6. (Tested with new Pillar syntax.)

**Comment by aboe76** [comment]
@dafyddj could you take another look and see if it ok and working?

**Comment by dafyddj** [comment]
LGTM. Thanks.

Tested on Debian Jessie and Windows 8.1. Old and new syntax.

**Pull request merged**
