### PR TITLE
fix(auth_nocache): Fix typo in client template

### PR DESCRIPTION
**Pull request by dimitry-unified-streaming**
This fixes an embarrassing typo in #125, causing the `auth_nocache`
setting not to work at all.

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by daks** [comment]
Good job spotting this typo :)

Do you think you could add some test to catch this error? If you need help, I can provide you some. Without looking in depth, I think you need to add this parameter in the pillar files used for tests declared here https://github.com/saltstack-formulas/openvpn-formula/blob/master/kitchen.yml#L191 and add a verification there https://github.com/saltstack-formulas/openvpn-formula/blob/master/test/integration/default/controls/config_spec.rb#L30

**Comment by myii** [comment]
@dimitry-unified-streaming Thanks for this.  In terms of the build, the commit message needs a slight tweak:

* https://travis-ci.com/saltstack-formulas/openvpn-formula/jobs/262125734#L365-L372

So:

```diff
-fix(auth_nocache): Fix typo in client template
+fix(auth_nocache): fix typo in client template
```

Worst case, this can be done using a squash merge using the GitHub UI.

**Comment by dimitry-unified-streaming** [comment]
> Do you think you could add some test to catch this error? If you need help, I can provide you some. Without looking in depth, I think you need to add this parameter in the pillar files used for tests declared here https://github.com/saltstack-formulas/openvpn-formula/blob/master/kitchen.yml#L191 and add a verification there https://github.com/saltstack-formulas/openvpn-formula/blob/master/test/integration/default/controls/config_spec.rb#L30

I'll try this when I have some more time, but I know next to nothing about the testing framework. :)  But I agree, it would be good to have at least a test that generates a config file and compares it to known good output.

**Comment by myii** [comment]
Thanks for the commit message fix, @dimitry-unified-streaming.  Can we go ahead and merge, @daks?

**Comment by daks** [comment]
ok for me

**Pull request merged**
