### PR TITLE
Consolidate map.jinja using split-out yaml files

### PR DESCRIPTION
**Pull request by dafyddj**
I want to add support for Windows to the formula, but before doing that I thought I would tidy up map.jinja, as there's a lot of duplication in there.

### CODE REVIEW

**Comment by aboe76** [comment]
@dafyddj couldn't a defaults.yaml setup be better? and more in line with the other formulas?
see salt-formula as an example.

**Comment by dafyddj** [comment]
Sure, that's possible. I thought using the base parameter was quite neat myself.

**Comment by alxwr** [comment]
@aboe76 @dafyddj looking forward to it!

**Comment by javierbertoli** [comment]
I'm too in favor of `defaults.yaml`, `osmap.yaml`, osfingermap.yaml`, etc., files. It's clearer, in my opinion. I used that approach in the [bareos formula](https://github.com/saltstack-formulas/bareos-formula), if you need an example to copy?

**Comment by dafyddj** [comment]
Ok, I'll look at this again.

**Comment by aboe76** [comment]
@dafyddj you are right that your solution is quite neat, but not consistent with other formulas. 
thanks for you efforts.!

**Comment by alxwr** [comment]
@dafyddj Thank you very much!

**Comment by alxwr** [comment]
Tested on FreeBSD 10.3, Debian 8.6 and Ubuntu 14.04.

**Comment by dafyddj** [comment]
Great. Thanks, I took @javierbertoli's lead.

**Pull request merged**
